
state_space:
  x_lower: -100.0
  x_upper: 100.0
  y_lower: -100.0
  y_upper: 100.0
  turning_radius: 10.0
  
planner_ros:
  nav_msgs_path_topic: ompl_rs_planner_ros/nav_msgs_path
  planning_service_name: ompl_rs_planner_ros/planning_service
  path_msg_topic: ompl_rs_planner_ros/nav_msgs_path
  path_frame: map
  nav_msg_path_spatial_resolution: 1.5

planner:
  path_spatial_resolution: 0.05
  ompl_planner: RRTstar # see ompl_planner_creators.hpp for list of available planners
  max_planning_time: 1.0
  
ompl_planners:
  rrt_star:
    planner_range: 50.0
  rrt_sharp:
    planner_range: 50.0